package Acme::CPANLists::Import::PerlAdvent::2009_12_04;

# DATE
# VERSION

our @Module_Lists = ({description=>"This list is generated by extracting module names mentioned in [http://perladvent.org/2009/4/] (retrieved on 2016-11-07). Visit the URL for the full contents.",entries=>[{module=>"Devel::Callsite"},{module=>"Every"},{module=>"Term::ProgressBar"}],summary=>"Modules mentioned in Perl Advent Calendar 2009 (day 4)"});

1;
# ABSTRACT: Modules mentioned in Perl Advent Calendar 2009 (day 4)

=head1 DESCRIPTION

This module is generated by extracting module names mentioned in L<http://perladvent.org/2009/4/> (retrieved on 2016-11-07). Visit the URL for the full contents.

