package Acme::CPANLists::Import::PerlAdvent::2009_12_24;

# DATE
# VERSION

our @Module_Lists = ({description=>"This list is generated by extracting module names mentioned in [http://perladvent.org/2009/24/] (retrieved on 2016-11-07). Visit the URL for the full contents.",entries=>[{module=>"lvalue"}],summary=>"Modules mentioned in Perl Advent Calendar 2009 (day 24)"});

1;
# ABSTRACT: Modules mentioned in Perl Advent Calendar 2009 (day 24)

=head1 DESCRIPTION

This module is generated by extracting module names mentioned in L<http://perladvent.org/2009/24/> (retrieved on 2016-11-07). Visit the URL for the full contents.

