package Acme::CPANLists::Import::PerlAdvent::2009;

# DATE
# VERSION

our @Module_Lists = ({description=>"This list is generated by extracting module names mentioned in [http://perladvent.org/2009/] (retrieved on 2016-11-07). Visit the URL for the full contents.",entries=>[{module=>"Any::Moose"},{module=>"Any::Moose::Convert"},{module=>"Moose"},{module=>"Mouse"},{module=>"List::AllUtils"},{module=>"List::EvenMoreUtils"},{module=>"List::MoreUtils"},{module=>"List::Util"},{module=>"Tie::CharArray"},{module=>"inc"},{module=>"local::lib"},{module=>"Devel::Callsite"},{module=>"Every"},{module=>"Term::ProgressBar"},{module=>"XML::Twig"},{module=>"Devel::Trace"},{module=>"Devel::Loaded"},{module=>"pmtools"},{module=>"DBIx::Class"}],summary=>"Modules mentioned in Perl Advent Calendar 2009"});

1;
# ABSTRACT: Modules mentioned in Perl Advent Calendar 2009

=head1 DESCRIPTION

This module is generated by extracting module names mentioned in L<http://perladvent.org/2009/> (retrieved on 2016-11-07). Visit the URL for the full contents.

