package Acme::CPANLists::Import::PerlAdvent::2009_12_01;

# DATE
# VERSION

our @Module_Lists = ({description=>"This list is generated by extracting module names mentioned in [http://perladvent.org/2009/1/] (retrieved on 2016-11-07). Visit the URL for the full contents.",entries=>[{module=>"Any::Moose"},{module=>"Any::Moose::Convert"},{module=>"Moose"},{module=>"Mouse"}],summary=>"Modules mentioned in Perl Advent Calendar 2009 (day 1)"});

1;
# ABSTRACT: Modules mentioned in Perl Advent Calendar 2009 (day 1)

=head1 DESCRIPTION

This module is generated by extracting module names mentioned in L<http://perladvent.org/2009/1/> (retrieved on 2016-11-07). Visit the URL for the full contents.

